CREATE TABLE "Periodos" (
	"ID"	INTEGER,
	"DataInicio"	TEXT NOT NULL,
	"HoraInicio"	TEXT NOT NULL,
	"DataFim"	TEXT,
	"HoraFim"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
)
CREATE TABLE Produtos (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome TEXT NOT NULL,
    Valor REAL NOT NULL,
    Quantidade INTEGER NOT NULL,
    DataEntrada TEXT NOT NULL,
    HoraEntrada TEXT NOT NULL,
    PeriodoID INTEGER,
    FOREIGN KEY (PeriodoID) REFERENCES Periodos(ID)
)
CREATE TABLE Vendas (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Data TEXT NOT NULL,
	Hora TEXT NOT NULL,
	Produto TEXT NOT NULL,
	Quantidade INTEGER NOT NULL,
	ValorTotal REAL NOT NULL,
	PeriodoID INTEGER NOT NULL,
	FOREIGN KEY (PeriodoID) REFERENCES Periodos(ID)
)